name: "ECR-ECS-Deployment"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter the name of the Environment to be deployed on'
        required: true
        type: string
        default: dev
permissions:
  id-token: write
  contents: read

jobs:
  ECR_ECS_Deployment:
    name: Build Docker Image And Push To ECR And Deploy To ECS
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:  
        - name: Checkout
          uses: actions/checkout@v2    
          
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{secrets.AWS_REGION}}

        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1


        - name: Login to Amazon ECR
          run: |
            aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}

        - name: Build, Tag, and Push Docker image to ECR
          run: |
            docker build -t my-image .
            docker tag my-image:latest ${{ secrets.AWS_ECR_REPO }}:latest
            docker push ${{ secrets.AWS_ECR_REPO }}:latest



        - name: ECR Status Check
          if: steps.containerImage.outcome == 'failure'
          run: exit 1